# -*- coding: utf-8 -*-
"""Modelo_Catboost.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v3yeKbRd6rUeVUaZ0UFTWo-2SAE6ugLO
"""

import pandas as pd
from catboost import CatBoostRegressor, Pool
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error,r2_score
import numpy as np
from sklearn.model_selection import KFold

from google.colab import drive
drive.mount('/content/drive')

df = pd.read_csv("/content/drive/MyDrive/Inmobiliario/datos_limpios_vivienda.csv")

df["tipo_propiedad"] = df["tipo_propiedad"].astype(str)
df["barrio"] = df["barrio"].astype(str)
df["antiguedad"] = df["antiguedad"].astype(str)

# Variables predictoras y variable objetivo
x = df[['tipo_propiedad', 'area', 'habitaciones', 'banos',
       'parqueaderos','antiguedad', 'permite_mascotas', 'gimnasio',
       'ascensor', 'conjunto_cerrado', 'piscina', 'salon_comunal', 'terraza',
       'vigilancia', 'barrio']]
y = np.log1p(df["precio_venta"])
# Dividir los datos en conjuntos de entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

pool_train = Pool(X_train, y_train, cat_features=["tipo_propiedad", "antiguedad", "barrio"])
pool_test = Pool(X_test, y_test, cat_features=["tipo_propiedad", "antiguedad", "barrio"])

# Grid Search
parametros = {
    "depth": [6, 8],
    "learning_rate": [0.03, 0.05],
    "l2_leaf_reg": [3, 5],
    "iterations": [1500, 2000]
}


catboost_modelo = CatBoostRegressor(
    eval_metric="RMSE",
    random_seed=42,
    verbose=False
)


gcv = GridSearchCV(
    estimator=catboost_modelo,
    param_grid=parametros,
    scoring="neg_root_mean_squared_error",
    cv=5,
    n_jobs=-1,
    verbose=2
)

gcv.fit(
    X_train,
    y_train,
    cat_features=["tipo_propiedad", "antiguedad", "barrio"]
)


modelo_final = CatBoostRegressor(
    **gcv.best_params_,
    eval_metric="RMSE",
    random_seed=42,
    verbose=100,
    use_best_model=True,
    early_stopping_rounds=100
)


modelo_final.fit(
    pool_train,
    eval_set=pool_test,  # Esto es necesario para use_best_model
)

# Predicciones en test
y_pred_log = modelo_final.predict(X_test)
y_pred = np.expm1(y_pred_log)
y_test_real = np.expm1(y_test)

# Métricas en test
rmse = np.sqrt(mean_squared_error(y_test_real, y_pred))
r2 = r2_score(y_test_real, y_pred)



print(f"R² real (test):   {r2:.3f}")

# Predicciones en train
y_pred_train = np.expm1(modelo_final.predict(X_train))
y_train_real = np.expm1(y_train)
r2_train = r2_score(y_train_real, y_pred_train)

print(f"R² (train):       {r2_train:.3f}")

# Guardar modelo entrenado
ruta = "/content/drive/MyDrive/Inmobiliario/catboost_modelo.cbm"
modelo_final.save_model(ruta)
print("Modelo guardado en:", ruta)